### ISSUE TITLE
Failed local tests - op_index.yml

### ISSUE THREAD

**Issue by cliveseldon** [k8s-operatorhub/community-operators#597] opened 2022-01-18 13:41 UTC
Running:

```
OP_TEST_DEBUG=3 bash <(curl -sL https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-pipeline/ci/latest/ci/scripts/opp.sh) kiwi,lemon,orange operators/seldon-operator/1.12.0
```

I get 

```
TASK [operator_index : Set versions and versions_bt] ***************************
task path: /playbooks/upstream/roles/operator_index/tasks/op_index.yml:64
fatal: [localhost]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'latest'
  
    The error appears to be in '/playbooks/upstream/roles/operator_index/tasks/op_index.yml': line 64, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: "Set versions and versions_bt"
      ^ here

PLAY RECAP *********************************************************************
localhost                  : ok=1006 changed=102  unreachable=0    failed=1    skipped=945  rescued=0    ignored=2   
```

Its very unclear how to solve this. Any ideas?

Its running in the image

```
quay.io/operator_testing/operator-test-playbooks:latest
```

I don't see this ansible script in https://github.com/redhat-openshift-ecosystem/operator-test-playbooks

**Comment by cliveseldon** [comment] 2022-01-18 18:04
@Jooho I made a [PR](https://github.com/k8s-operatorhub/community-operators/pull/599) but it fails for other reasons. Happy to chat outside this issue on these.

**Comment by cliveseldon** [comment] 2022-01-19 11:29
Locally `kiwi` and `lemon` tests succeed and I see `orange` is not run here. So maybe this is a non-bug as its only for upstream tests and we can close?

**Comment by camilamacedo86** [comment] 2022-02-04 13:50
Hi @cliveseldon, 

I am adding below what was added in the PR as a comment as well. 

The issue in this repo would **not** be caused because. of:

```
will reopen and add com.redhat.openshift.versions: "v4.8" to latest annotations which was missing.
```

This annotation is only required / valid for [k8s-operatorhub/community-operators/operators](https://github.com/k8s-operatorhub/community-operators/tree/main/operators) and not to publish here. It is not used here at all. 

The error faced is: ( You can check it [here](https://github.com/k8s-operatorhub/community-operators/runs/4857188343?check_suite_focus=true#step:6:937)) 

```
 stdout: |-
    time="2022-01-18T17:49:04Z" level=error msg="Error: Value seldon-manager: invalid service account found in bundle. sa name cannot match service account defined for deployment spec in CSV"
```

The root cause for this one is the SA. This shows that you are defining SA outside of the CSV and in the CSV. (E.g.: https://github.com/cliveseldon/community-operators-1/blob/d7f293919873b4e99342151754bd7756d85572c2/operators/seldon-operator/1.5.0/manifests/seldon-manager_v1_serviceaccount.yaml)

AND (See [here](https://github.com/k8s-operatorhub/community-operators/runs/4857188186?check_suite_focus=true))

```
    time="2022-01-18T17:50:07Z" level=error msg="permissive mode disabled" bundles="[kind-registry:5000/test-operator/seldon-operator:v1.5.0 kind-registry:5000/test-operator/seldon-operator:v1.6.0 kind-registry:5000/test-operator/seldon-operator:v1.7.0 kind-registry:5000/test-operator/seldon-operator:v1.11.1 kind-registry:5000/test-operator/seldon-operator:v1.12.0]" error="unable to determine default channel among channel heads: map[alpha:{name:seldon-operator.v1.12.0 version:{Major:1 Minor:12 Patch:0 Pre:[] Build:[]} count:1}]"
    Error: unable to determine default channel among channel heads: map[alpha:{name:seldon-operator.v1.12.0 version:{Major:1 Minor:12 Patch:0 Pre:[] Build:[]} count:1}]

```

The above error occurs with the wrong OLM upgrade graph configurations. To know more about how to configure the upgrade graph see: https://v0-18-z.olm.operatorframework.io/docs/concepts/olm-architecture/operator-catalog/creating-an-update-graph/

You are defining invalid paths and channels. 
The paths are defined via the skips/replaces/skipRange directrizes 
And the channels are defined via the annotations ([`seldon-operator/1.7.0/metadata/annotations.yaml`](https://github.com/cliveseldon/community-operators-1/blob/d7f293919873b4e99342151754bd7756d85572c2/operators/seldon-operator/1.7.0/metadata/annotations.yaml#L7-L9)), see:

```
 operators.operatorframework.io.bundle.channels.v1: alpha
  operators.operatorframework.io.bundle.channel.default.v1: stable
```

So, let's check the above e.g used to configure bundle 1.7.0. 
You defined that it should be distributed via the channels alpha and stable.

And then, that this bundle should replace `replaces: seldon-operator.v1.6.0`(https://github.com/cliveseldon/community-operators-1/blob/d7f293919873b4e99342151754bd7756d85572c2/operators/seldon-operator/1.7.0/metadata/annotations.yaml#L7-L9). 

In this way, you need to check if all paths are valid configurations. 
I'd recommend you change only one bundle per PR instead of sending many changes at once. 

Additionally, about testing the Operator bundle and avoiding these scenarios I'd recommend you always ensure that you are using the latest SDK client version and run the command `operator-sdk bundle validate ./bundle --select-optional suite=operatorframework
` with it to check your bundle before pushing the PR. More info: https://olm.operatorframework.io/docs/best-practices/common/

I hope that it helps you out.  

Since you also already close the PR and the info above was provided I am closing this one. However, if you face any new issues or have any questions/concerns please feel free to raise new issues.

**Closed by camilamacedo86** 2022-02-04 13:50 UTC
